#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyproject_hooks', 'pyproject_hooks._in_process']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='pyproject_hooks',
      version='1.1.0',
      description='Wrappers to call pyproject.toml-based build backend hooks.',
      author=None,
      author_email='Thomas Kluyver <thomas@kluyver.me.uk>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      python_requires='>=3.7',
     )
